import Link from "next/link";

const features = [
  ["Live product sourcing", "Import real S&S styles, colors, prices, inventory, images, and exact SKUs."],
  ["Production-aware pricing", "Quote Screen Print, DTF, and Embroidery from supplier cost, quantity, and method rules."],
  ["Customer-ready checkout", "Collect artwork, sizes, mockups, and secure payment without sending customers elsewhere."],
  ["Shop operations", "Move paid orders from artwork review to blank ordering and production."],
];

export default function HomePage(){
 return <main className="launch-site">
  <nav className="launch-nav"><Link href="/" className="launch-wordmark"><span>PF</span> PRINTFLOW</Link><div><a href="#platform">Platform</a><a href="#workflow">Workflow</a><Link href="/login">Sign in</Link><Link href="/signup" className="launch-nav-cta">Start your shop</Link></div></nav>
  <section className="launch-hero"><div className="launch-hero-copy"><p className="launch-kicker">CUSTOM APPAREL COMMERCE, BUILT FOR PRINTERS</p><h1>From blank garment to paid production order.</h1><p>PrintFlow gives print shops a branded storefront, live supplier catalog, method-based pricing, secure checkout, and production files in one professional system.</p><div className="launch-hero-actions"><Link className="launch-primary" href="/signup">Create your shop</Link><Link className="launch-secondary" href="/login">Open dashboard</Link></div><div className="launch-mini-proof"><span>Live payments</span><span>Supplier SKUs</span><span>100 MB artwork</span><span>Front + back mockups</span></div></div>
  <div className="launch-product-preview"><div className="launch-preview-top"><span>NEW ORDER</span><b>Ready to quote</b></div><div className="launch-preview-body"><div className="launch-shirt-visual"><div>PF</div></div><div className="launch-preview-lines"><span>Premium heavyweight tee</span><strong>48 garments</strong><small>Front screen print · 2 colors</small><small>Back full print · 1 color</small></div></div><div className="launch-preview-total"><span>Verified customer total</span><strong>$1,248.00</strong></div></div></section>
  <section className="launch-logo-strip"><span>SUPPLIER</span><b>S&amp;S ACTIVEWEAR</b><span>PAYMENTS</span><b>STRIPE</b><b>SQUARE</b><span>METHODS</span><b>SCREEN PRINT · DTF · EMBROIDERY</b></section>
  <section id="platform" className="launch-feature-section"><div className="launch-section-heading"><p className="launch-kicker">ONE OPERATING SYSTEM</p><h2>Everything the order needs stays connected.</h2></div><div className="launch-feature-grid">{features.map(([title,copy],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section id="workflow" className="launch-workflow"><div><p className="launch-kicker">THE CUSTOMER JOURNEY</p><h2>Simple enough for anyone to order shirts.</h2><p>Customers pick a product, select colors and quantities, choose their print method, upload artwork, approve mockups, and pay through the shop’s connected provider.</p><Link className="launch-primary" href="/signup">Build your storefront</Link></div><ol><li><span>1</span><div><b>Choose the blank</b><small>Real supplier and manual products in one catalog.</small></div></li><li><span>2</span><div><b>Build the print</b><small>Front, back, Heart Size, Full Size, method, color count.</small></div></li><li><span>3</span><div><b>Get the live price</b><small>Supplier cost, markup, production rules, and quantity breaks.</small></div></li><li><span>4</span><div><b>Upload and pay</b><small>Production artwork, saved mockups, hosted checkout.</small></div></li></ol></section>
  <section className="launch-final-cta"><p className="launch-kicker">READY TO PROCESS REAL ORDERS?</p><h2>Launch your PrintFlow shop.</h2><p>Set up the account, connect payments and S&S, configure pricing, and publish your customer page.</p><Link className="launch-primary light" href="/signup">Create an account</Link></section>
  <footer className="launch-footer"><Link href="/" className="launch-wordmark"><span>PF</span> PRINTFLOW</Link><p>Custom apparel commerce and production operations.</p><div><Link href="/login">Sign in</Link><Link href="/signup">Create account</Link></div></footer>
 </main>;
}
