"use client";
import { useState } from "react";

type Connection = { provider: string; category: string; status: string; account_label?: string; last_tested_at?: string; last_error?: string };
type Definition = { provider: string; name: string; category: string; initials: string; description: string; note?: string; fields: { key: string; label: string; type?: string; placeholder?: string }[] };
const definitions: Definition[] = [
  { provider: "stripe", name: "Stripe", category: "payment", initials: "ST", description: "Native card payments, refunds and payment status.", fields: [{ key: "secretKey", label: "Restricted or secret API key", type: "password", placeholder: "sk_live_…" }] },
  { provider: "square", name: "Square", category: "payment", initials: "SQ", description: "Payments, locations and future Square catalog support.", fields: [{ key: "accessToken", label: "Access token", type: "password" }, { key: "environment", label: "Environment", placeholder: "production or sandbox" }] },
  { provider: "squarespace", name: "Squarespace Commerce", category: "commerce", initials: "SS", description: "Orders, products, inventory and transaction synchronization.", fields: [{ key: "apiKey", label: "Commerce API key", type: "password" }] },
  { provider: "shopify", name: "Shopify", category: "commerce", initials: "SH", description: "Store products, orders and checkout handoff.", note: "Custom-app token mode. Public app OAuth can be added before marketplace launch.", fields: [{ key: "shopDomain", label: "Shop domain", placeholder: "store.myshopify.com" }, { key: "accessToken", label: "Admin API access token", type: "password" }] },
  { provider: "google-drive", name: "Google Drive", category: "files", initials: "GD", description: "Deliver artwork, mockups and production sheets to a shop folder.", fields: [{ key: "serviceAccountJson", label: "Service account JSON", type: "textarea" }, { key: "folderId", label: "Destination folder ID" }] },
  { provider: "sanmar", name: "SanMar", category: "supplier", initials: "SM", description: "Future catalog, inventory and blank-order connector.", note: "Credentials are stored now; live API mapping requires SanMar integration access.", fields: [{ key: "accountNumber", label: "Account number" }, { key: "apiCredential", label: "API credential", type: "password" }] },
  { provider: "alphabroder", name: "AlphaBroder", category: "supplier", initials: "AB", description: "Future blank catalog and ordering connector.", note: "Credentials are stored now; live API mapping requires provider approval.", fields: [{ key: "accountNumber", label: "Account number" }, { key: "apiCredential", label: "API credential", type: "password" }] }
];
export default function IntegrationCenter({ initialConnections }: { initialConnections: Connection[] }) {
  const [connections, setConnections] = useState(initialConnections); const [open, setOpen] = useState<Definition | null>(null); const [values, setValues] = useState<Record<string,string>>({}); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function connect() { if (!open) return; setBusy(true); setMessage(""); const response = await fetch("/api/admin/integrations/connections", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider: open.provider, category: open.category, credentials: values }) }); const data = await response.json(); setBusy(false); if (!response.ok || !data.ok) return setMessage(data.error || "Connection failed."); setConnections((current) => [...current.filter((item) => item.provider !== open.provider), { provider: open.provider, category: open.category, status: "connected", account_label: data.accountLabel, last_tested_at: new Date().toISOString() }]); setMessage("Connected and encrypted."); }
  async function disconnect(provider: string) { if (!confirm("Disconnect this integration?")) return; await fetch(`/api/admin/integrations/connections?provider=${provider}`, { method: "DELETE" }); setConnections((current) => current.filter((item) => item.provider !== provider)); setOpen(null); }
  return <><div className="integration-center-grid">{definitions.map((item) => { const connection = connections.find((c) => c.provider === item.provider); return <article className="admin-card integration-vault-card" key={item.provider}><div className="integration-vault-icon">{item.initials}</div><div className="integration-vault-copy"><div className="card-heading"><div><p className="eyebrow">{item.category}</p><h2>{item.name}</h2></div><span className={connection?.status === "connected" ? "status-pill connected" : connection?.status === "error" ? "status-pill error" : "status-pill"}>{connection?.status || "Not connected"}</span></div><p>{item.description}</p>{connection?.account_label && <small>{connection.account_label}</small>}{connection?.last_error && <small className="integration-error">{connection.last_error}</small>}</div><button className="secondary-button fit-button" onClick={() => { setOpen(item); setValues({}); setMessage(""); }}>{connection ? "Manage" : "Connect"}</button></article>; })}</div>
  {open && <div className="modal-backdrop" onMouseDown={() => setOpen(null)}><section className="integration-modal" onMouseDown={(e) => e.stopPropagation()}><button className="modal-close" onClick={() => setOpen(null)}>×</button><p className="eyebrow">CONNECT {open.category.toUpperCase()}</p><h2>{open.name}</h2><p>{open.description}</p>{open.note && <div className="integration-note">{open.note}</div>}<div className="integration-form">{open.fields.map((field) => <label key={field.key}><span>{field.label}</span>{field.type === "textarea" ? <textarea rows={7} value={values[field.key] || ""} onChange={(e) => setValues({ ...values, [field.key]: e.target.value })}/> : <input type={field.type || "text"} placeholder={field.placeholder} value={values[field.key] || ""} onChange={(e) => setValues({ ...values, [field.key]: e.target.value })}/>}</label>)}</div>{message && <div className={message.startsWith("Connected") ? "success-message" : "error-message"}>{message}</div>}<div className="integration-modal-actions">{connections.some((item) => item.provider === open.provider) && <button className="danger-button" onClick={() => disconnect(open.provider)}>Disconnect</button>}<button className="primary-button" disabled={busy} onClick={connect}>{busy ? "Testing…" : "Save & test connection"}</button></div><small>Credentials are encrypted with PRINTFLOW_ENCRYPTION_KEY and never returned to the browser after saving.</small></section></div>}</>;
}
