import Link from "next/link";
import SSActivewearIntegration from "@/components/SSActivewearIntegration";

type Props={ssSupplier:any;sanmarConnection:any;productCount:number;draftCount:number};
export default function SupplierHub({ssSupplier,productCount,draftCount}:Props){const connected=ssSupplier?.status==="connected";return <>
 <section className="supplier-stat-grid polished"><div className="admin-card"><span>Imported supplier products</span><strong>{productCount}</strong><small>Products using live supplier SKUs</small></div><div className="admin-card"><span>Blank drafts ready</span><strong>{draftCount}</strong><small>Paid jobs prepared for purchasing</small></div><div className="admin-card"><span>Live suppliers</span><strong>{connected?1:0}</strong><small>Operational catalog connections</small></div></section>
 <section className="supplier-equal-grid production-suppliers"><article className="admin-card supplier-equal-card"><header><div className="provider-mark">S&amp;S</div><span className={connected?"status-pill connected":"status-pill"}>{connected?"Live":"Setup needed"}</span></header><div><p className="eyebrow">WHOLESALE SUPPLIER</p><h2>S&amp;S Activewear</h2><p>Live product search, account pricing, inventory, exact SKUs, product imports, and blank ordering. AlphaBroder operates through S&amp;S.</p></div><footer><Link className="secondary-button" href="#ss-settings">{connected?"Manage connection":"Connect account"}</Link>{connected&&<Link className="text-button" href="/dashboard/suppliers/catalog">Browse live catalog →</Link>}</footer></article>
 <article className="admin-card supplier-equal-card"><header><div className="provider-mark">＋</div><span className="status-pill connected">Available</span></header><div><p className="eyebrow">OWN INVENTORY</p><h2>Manual products</h2><p>Create a product from local inventory or any specialty supplier, set its real cost, and upload front/back mockups for every color.</p></div><footer><Link className="secondary-button" href="/dashboard/products">Create a product</Link><span className="supplier-card-note">Uses the same storefront and production pricing.</span></footer></article>
 <article className="admin-card supplier-equal-card roadmap"><header><div className="provider-mark">SM</div><span className="status-pill">Roadmap</span></header><div><p className="eyebrow">FUTURE CONNECTOR</p><h2>SanMar</h2><p>Not connectable until PrintFlow supports a verified live catalog and ordering workflow. No placeholder credential storage is presented as a working integration.</p></div><footer><span className="supplier-card-note">Coming after approved API implementation.</span></footer></article></section>
 <section id="ss-settings" className="supplier-connection-section"><div className="supplier-section-heading"><div><p className="eyebrow">S&amp;S CONNECTION</p><h2>Live catalog and ordering controls</h2><p>Use production mode when the shop is ready to submit real wholesale orders.</p></div><Link className="secondary-button" href="/dashboard/integrations">View integrations</Link></div><SSActivewearIntegration connected={connected} accountHint={ssSupplier?.account_hint} initialSettings={ssSupplier?.settings}/></section>
 </>}
